/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    InfoIcon: typeof import('./src/components/InfoIcon.vue')['default']
    MeetingNameDisplay: typeof import('./src/components/MeetingNameDisplay.vue')['default']
    OpenRenameMeetingDialog: typeof import('./src/components/OpenRenameMeetingDialog.vue')['default']
    PrivacyOverlay: typeof import('./src/components/PrivacyOverlay.vue')['default']
    RenameMeetingDialog: typeof import('./src/components/RenameMeetingDialog.vue')['default']
    ResetAppStateDialog: typeof import('./src/components/ResetAppStateDialog.vue')['default']
    ResourceEditor: typeof import('./src/components/ResourceEditor.vue')['default']
    ResourceInput: typeof import('./src/components/ResourceInput.vue')['default']
    SetElapsedTimeDialog: typeof import('./src/components/SetElapsedTimeDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SwitchThemeListItem: typeof import('./src/components/SwitchThemeListItem.vue')['default']
    TimerControls: typeof import('./src/components/TimerControls.vue')['default']
    TimerDisplay: typeof import('./src/components/TimerDisplay.vue')['default']
    WastedMoney: typeof import('./src/components/WastedMoney.vue')['default']
  }
}
